name: Agent Task
description: Internal task for an agent to execute
title: "[Task] "
labels: ["agent-task"]
body:
  - type: dropdown
    id: agent
    attributes:
      label: Assigned Agent
      options:
        - Coordinator
        - Site Builder
        - Content Writer
        - Docs Author
        - Slide Designer
        - DevOps
        - Rust Engineer
        - Brand/Design
        - QA/Reviewer
        - Data Engineer
        - Security/Compliance
    validations:
      required: true
  - type: textarea
    id: task
    attributes:
      label: Task Description
      description: What needs to be done? Be specific.
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How do we know this is done?
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0 - Critical
        - P1 - High
        - P2 - Medium
        - P3 - Low
    validations:
      required: true
