name: Improvement
description: Suggest an improvement to something that already exists
title: "[Improve] "
labels: ["improvement"]
body:
  - type: textarea
    id: current
    attributes:
      label: Current State
      description: What exists today?
    validations:
      required: true
  - type: textarea
    id: proposed
    attributes:
      label: Proposed Improvement
      description: What should change and why?
    validations:
      required: true
  - type: dropdown
    id: agent
    attributes:
      label: Assigned Agent
      options:
        - Coordinator
        - Site Builder
        - Content Writer
        - Docs Author
        - Slide Designer
        - DevOps
        - Rust Engineer
        - Brand/Design
        - QA/Reviewer
        - Data Engineer
        - Security/Compliance
    validations:
      required: false
